# Generated by Django 2.2.8 on 2020-01-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
