# Generated by Django 2.2.8 on 2020-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200101_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='location_photos'),
        ),
    ]
